classDiagram
    class Storage{
        +String ssid
        +String password
        +String deviceName
        +String getSSID()
        +String getPassword()
        +String getDeviceName()
        +void setSSID(String ssid)
        +void setPassword(String password)
        +void setDeviceName(String name)
        +bool save()
        +bool load()
        +bool clear()   
    }
